Feat/basic structure
VladimirM89/Airways pull request #1
Opened 2023-04-13 14:59 UTC by VladimirM89

Implements: 
- add basic project structure
 - add eslint airbnb and prettier configs
 - add routing with lazy-loading modules

2023-04-13 15:52 UTC, Ponomareva-Nina requested changes

2023-04-13 15:52 UTC, Ponomareva-Nina commented on src/app/shared/shared.component.html
no need

2023-04-13 15:52 UTC, Ponomareva-Nina commented on src/app/core/core.component.ts
no need of component in here. Instead of it - we need a module

2023-04-14 08:33 UTC, VladimirM89 commented on src/app/shared/shared.component.ts
fix

2023-04-14 08:33 UTC, VladimirM89 commented on src/app/shared/shared.component.html
fix

2023-04-14 08:33 UTC, VladimirM89 commented on src/app/core/core.component.ts
fix

2023-04-14 08:33 UTC, VladimirM89 commented on src/app/core/core.component.html
fix

2023-04-14 14:10 UTC, avkomosko approved these changes

2023-04-14 14:12 UTC, Ponomareva-Nina approved these changes
good job

2023-04-16 18:51 UTC, Alextufeng approved these changes

2023-04-16 21:16 UTC, merged